server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/cart
    driver-class-name: org.postgresql.Driver
    username: cart_user
    password: password3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 50
        failure-rate-threshold: 50
    instances:
      warehouse:
        sliding-window-size: 10
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true