server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/smarthome
    driver-class-name: org.postgresql.Driver
    username: smart
    password: home
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    warehouse:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

feign:
  client:
    config:
      warehouse:
        url: http://warehouse/api/v1/warehouse