server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/cart
    driver-class-name: org.postgresql.Driver
    username: cart_user
    password: password3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
  timelimiter:
    configs:
      default:
        timeout-duration: 5s