CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR,
    city VARCHAR,
    street VARCHAR,
    house VARCHAR,
    flat VARCHAR
);

CREATE TABLE IF NOT EXISTS deliveries (
    delivery_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    from_address BIGINT REFERENCES addresses(id),
    to_address BIGINT REFERENCES addresses(id),
    order_id UUID,
    delivery_state VARCHAR
);