spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000