grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  consumer:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}

analyzer:
  topic:
    sensors:
      v1: telemetry.sensors.v1
    snapshots:
      v1: telemetry.snapshots.v1
    hubs:
      v1: telemetry.hubs.v1