server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/store
    driver-class-name: org.postgresql.Driver
    username: store_user
    password: password2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      zalando:
        logbook: TRACE